### ISSUE TITLE
Make a slide about Hacktoberfest!

### ISSUE THREAD

**Issue by Eckankar** [kantinen/infoscreen#11]
Can be a HTML page. Should render correctly on a 1920x1080 webkit. See other examples in content folder.

https://hacktoberfest.digitalocean.com/

**Comment by JamesFranc** [comment]
I'll go ahead and take a look at this today.

**Comment by Eckankar** [comment]
Something like https://github.com/datalogisk-kantineforening/infoscreen/blob/master/content/dm-i-programmering-2016.html or https://github.com/datalogisk-kantineforening/infoscreen/blob/master/content-disabled/dm_warmup_konkurrence.html could be used as inspiration.

It's for an infoscreen in the students' area of the CS department of University of Copenhagen. Silly is perfectly allowed.

**Comment by JamesFranc** [comment]
Silly is wonderful, thank you for the reference!

**Comment by JamesFranc** [comment]
#13 submitted pull request (not sure about the etiquette for this)

**Comment by nqpz** [comment]
Thanks for your effort, but you have misunderstood Eckankars link.  You should not replace the "DM i Programmering" slide (which means "The Danish Championship in Programming"), but instead create a slide _just_ about Hacktoberfest.  The inspirational HTML files were meant to be modified a great deal.

Actually, I would like to contradict Eckankar and provide you with some other inspiration!  His slides always contain lots of external Javascript and CSS and whatnot.  My slide at https://github.com/datalogisk-kantineforening/infoscreen/blob/master/content/emacs.html is much simpler, but still pretty.

**Comment by JamesFranc** [comment]
Sorry for the misunderstanding. Thanks for the additional details!

Newest commit should have something more in line with what you're looking for, just let me know if you'd like anything changed.

**Comment by nqpz** [comment]
I have merged your pull request.  Nice!  It will now be shown throughout the rest of October in our student canteen at the CS dept. of the University of Copenhagen.
