### ISSUE TITLE
blinkende lygter

### ISSUE THREAD

**Issue by PtxDK** [kantinen/infoscreen#38]
Altså jeg vil heller ikke misse denne yderst vigtige begivenhed. Men behøves det at være så blinkende at man får spat af og sidde i kantinen?

https://github.com/datalogisk-kantineforening/infoscreen/blob/77fe12c70390f51a63bc3ff67bf2a0f3d3c66a63/content/most_important_thing_ever.html#L31

**Comment by athas** [comment]
Pull requests welcome!

**Comment by Thraundil** [comment]
Jeg har fixet det
