### ISSUE TITLE
Nyt infoslide om infoskærmen

### ISSUE THREAD

**Issue by nqpz** [kantinen/infoscreen#39]
`git blame content/infoscreen.html` fortæller mig at infoskærmsslidet på infoskærmen sidst blev opdateret i februar 2016.  Det er snart to år siden!

Vil nogen ikke nok lave et nyt?  Der skal stå på det at det er infoskærmen og at man kan bidrage slides via GitHub.

**Comment by oleks** [comment]
Det er måske også et passende tilspunkt til at flytte `infoscreen` over til [`kantinen`](https://github.com/kantinen)? Er der noget man ødelægger ved at "bare" gøre det?

**Comment by nqpz** [comment]
On Wed, 08 Nov 2017 13:45:48 +0000, Oleks wrote:
> Det er måske også et passende tilspunkt til at flytte `infoscreen` over til `kantinen`?

Fint med mig.

**Comment by einar-io** [comment]
Blev det her nogensinde udført, eller er det her stadigvæk et ønske?

**Comment by nqpz** [comment]
Kan man gøre det nemt? Så synes jeg bare at man skal gøre det.

Sig til hvis I mangler rettigheder. Jeg kan vist stadig tildele admin-rettigheder.

**Comment by LedErik** [comment]
Tror det eneste er at det cronjob som haler fra git (eller scriptet det starter som gør det) lige skal rettes til det nye arkivs adresse.
