### ISSUE TITLE
Denne grube må flyttes!

### ISSUE THREAD

**Issue by oleks** [kantinen/infoscreen#61]
Kantinen ejer også det meget mere belejlige GitHub-organizationsnavn, [kantinen](https://github.com/kantinen/). Jeg synes tiden er inde at flytte infoscreen dertil.

Hvad går der galt hvis vi bare går hen og gør det? @athas @nqpz

**Comment by athas** [comment]
Jeg synes kun det skal gøres hvis du selv reparerer det (dvs. du bør også være i kantinen så du kan se om det virker).  Derudover er der ingen grund til at ændre noget der fungerer.

**Comment by oleks** [comment]
> Derudover er der ingen grund til at ændre noget der fungerer.

@athas refaktorer du heller ikke din kode?

**Comment by truls** [comment]
> Kantinen ejer også det meget mere belejlige GitHub-organizationsnavn, [kantinen](https://github.com/kantinen/). Jeg synes tiden er inde at flytte infoscreen dertil.
> 
> Hvad går der galt hvis vi bare går hen og gør det? @athas @nqpz

Det ser ud som om at du bare kan gøre det

> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. 

fra: https://help.github.com/articles/transferring-a-repository/

**Comment by nqpz** [comment]
Jeg synes at vi skal prøve at spørge @einar-io eller @BeneCollyridam om de har lyst til at stå for flytningen.  Det er vist dem der merger flest pull requests i øjeblikket.

**Comment by oleks** [comment]
> Det ser ud som om at du bare kan gøre det

Jo, men det kan man ikke kalde for at "flytte". For der er potentielt (omend ca. 0%) chance for at der kommer nogen og vil have datalogisk-kantineforening/infoscreen til et andet formål, og SÅ går det galt for infoskærmen.

Men idéen med at flytte infoscreen er også at datalogisk-kantineforening kan dø en stille død, og bag det hægte du henviste til står der ikke noget om hvad der sker med de hægter når den oprindelige organization lukker ned.

**Comment by BeneCollyridam** [comment]
Jeg flytter det nu, hvis der er nogen, som vil give mig adgang til [kantinen](https://github.com/kantinen/)?
@oleks

**Comment by nqpz** [comment]
Jeg har vist gjort dig til Owner nu.
