### ISSUE TITLE
Nyt infoslide om infoskærmen

### ISSUE THREAD

**Issue by nqpz** [kantinen/infoscreen#62]
`git blame content/infoscreen.html` fortæller mig at infoskærmsslidet på infoskærmen sidst blev opdateret i februar 2016. Det er snart tre år siden!

Vil nogen ikke nok lave et nyt?  Nu har der reelt været gratis Star Wars-reklame i lang tid nok. Der skal stå på slidet at det er infoskærmen og at man kan bidrage slides via GitHub.  Nu er der jo også kommet en fin ny (kortere) GitHub URL.

**Comment by 0undefined** [comment]
bump.
Det er snart 5 år siden
